### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Luz1727#1]
[Infografia-LuzArleth-TypeScript.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Luz1727/files/15204573/Infografia-LuzArleth-TypeScript.pdf)

**Comment by ToniDepp** [comment]
Partes de la infografía: 20/20
Coherencia y pertinencia: 20/20
Organización de la información: 15/20
Diseño de la infografía: 15/20
Creatividad: 15/20

Resultado: 17%/20%

**Comment by josealfredo79** [comment]
bien hecho y revisado
